version: '3.7'

services:
   db:
     image: postgres:12.2
     volumes:
       - /home/docker/volumes/postgres:/var/lib/postgresql/data
     restart: always
     environment:
       - POSTGRES_PASSWORD=postgres 
       - TZ=IST-1
   web:
     depends_on:
       - db
     image: registry.gitlab.com/loganathanr/jays-gala-app:latest
     ports:
       - "8084:8084"
     restart: always
     environment:
       - TZ=IST-1
   adminer:
     depends_on:
       - db
     image: adminer
     ports:
       - "8080:8080"
     restart: always
     environment:
       - TZ=IST-1
